name: churn_model
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: istywhyerlina/mlops_demo_1
    container_name: mlops_demo_1
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: unless-stopped

  app-1:
    image: istywhyerlina/mlops_demo_1
    container_name: app_1
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: unless-stopped

  app-2:
    image: istywhyerlina/mlops_demo_1
    container_name: app_2
    ports:
      - 8081:8080
    env_file:
      - .env
    restart: unless-stopped

  app-3:
    image: istywhyerlina/mlops_demo_1
    container_name: app_3
    ports:
      - 8082:8080
    env_file:
      - .env
    restart: unless-stopped
      