name: CD_STAGE
	on:
	  push:
	    branches: [ "main" ]
	permissions:
	  contents: read
	jobs:
	  build-push:
	    runs-on: ubuntu-latest
	    steps:
	    - uses: actions/checkout@v4
	    - name: Set up Python 3.12
	      uses: actions/setup-python@v3
	      with:
	        python-version: "3.12"
	    - name: Login to Docker Hub
	      uses: docker/login-action@v2
	      with:
	        username: ${{ secrets.DOCKER_HUB_USER }}
	        password: ${{ secrets.DOCKER_HUB_TOKEN }}
	    - name: Create .env File
	      run: |
	        echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> .env
	        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> .env
	        echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
	        echo "MODEL_ALIAS=${{ secrets.MODEL_ALIAS_STAGE }}" >> .env
	    - name: Build Container
	      run: |
	        docker compose build
	        docker compose push
  
